- .gitignore
- README.md
- app/routes.py
- app/services/cypher_generator.py
- app/services/metta_generator.py
- config/config.yaml
- curl.txt
- requirements.txt
* Added logging setup and replaced print statements with exception logging.
* Removed id and synonyms
* Add Flask_CORS for handling corss-origin requests
* Update README file
* Added a helper function to process Cypher files
* Simplified query generation for cases without predicates.
* Standardized response formatting for Cypher and MeTTa results.
> Improve Logging, Error Handling, and Response Consistency

- .gitignore
- app/lib/validator.py
- app/services/cypher_generator.py
- app/services/metta_generator.py
- app/services/schema_data.py
* Fixed cartesian product in cypher queries 
* Handled Ensemble ID queries
* Update validator for handling request without predicates
* Processed schema even further
* update metta query generator based on the new schema
> Fix Cartesian Product, Support Ensemble ID Queries, and Update Validator, Preprocess schema

- app/lib/__init__.py
- app/lib/limit_graph.py
- app/lib/map_graph.py
- app/routes.py
- config/config.yaml
* Added a function to limit the number of nodes displayed based on a threshold.
* Ensured that no connected edges are truncated when limiting node
> Limit Node Display by Threshold

- README.md
- app/lib/__init__.py
- app/lib/email.py
- app/routes.py
- app/services/cypher_generator.py
- app/services/metta_generator.py
- app/services/query_generator_interface.py
- config/schema_config.yaml
- requirements.txt
* **Updated README**: Added instructions on how to set up a limit for the maximum number of nodes to send.
* **New Endpoint  ``email-query``:** Created a new endpoint that processes queries and sends the results via email. The response includes an XLS file containing multiple sheets.
* Add safeguard for limit the node
* fix issue with chain based query
> New Endpoint for Email Queries and README Enhancements

- README.md
- app/lib/email.py
- app/routes.py
- app/services/cypher_generator.py
- app/services/metta_generator.py
- app/services/query_generator_interface.py
- config/config.yaml
Here's a detailed description for each part of your pull request:
1. **Update README for Flask-Mail Configuration**:
2. **Convert ID to Lowercase for Cypher Queries**:
- Modified the ID handling logic to convert gene and transcript IDs to lowercase when querying Neo4j.
- Ensured that if the ID does not start with 'ENSG' or 'ENST', the `gene_name` or `transcript_name` properties are used instead for more accurate matching.
3. **Optimize Node Property Selection**:
- add query string `properties` that can be either true or false. if true it will return only the name else it will return all the properties 
- For `gene` nodes, send the `gene_name` property (if properties is set to false).
- For `transcript` nodes, send the `transcript_name` property(if properties is set to false).
- For …
> Update README for Flask-Mail Configuration, Refactor ID Handling, and Optimize Node Property Selection

- app/services/cypher_generator.py
Fixed issue that arises from setting the query string to false or omitting it
> Resolve issue with omitted or false query string in requests

- README.md
- app/lib/__init__.py
- app/lib/auth.py
- app/lib/validator.py
- app/models/__init__.py
- app/models/storage.py
- app/persistence/storage_service.py
- app/routes.py
- app/services/__init__.py
- app/services/cypher_generator.py
- app/services/graph_handler.py
- app/services/llm_handler.py
- app/services/llm_models.py
- db.py
- requirements.txt
- tests/conftest.py
- tests/integration/cypher/conftest.py
- tests/integration/cypher/test_cypher_response.py
- tests/integration/test_response.py
- tests/lib/header_generator.py
- tests/unit/test_validatory.py
- **Integrate Authentication**: Integrate authentication service with the annotation service  
- **Fix in `parse_id` Function**: resolved the previous issue where case sensitivity was enforced.
- **Unit Tests for Validator**: Added comprehensive unit tests for the validator
- **Integration Tests for Cypher**: Implemented integration tests to validate the Cypher queries
- Added Integration tests for **Get Nodes**, **Get Relations** and **Get Edges**
- Add more validation to handle duplicate node_ids
> Fix Ensemble ID Parsing and Port Tests

- Data/graph_info.json
- app/routes.py
- app/services/schema_data.py
- add graph_info.json
- implement route for graph info endpoint
> Graph info endpoint

- .github/workflows/main.yml
- Renamed the workflow to Annotation-Service for clearer identification.
- Implemented caching for Python dependencies to speed up installation in subsequent runs.
> Optimize Annotation-Service Workflow

- Dockerfile
- README.md
- docker-compose.yml
- run.sh
- Add bash script to automate deployment
> Automate Deployment

- Dockerfile
- README.md
- docker-compose.yml
- run.py
- run.sh
Replaced hardcoded values (such as ports, Docker Hub repository, and MongoDB connection) with environment variables in the deployment scripts and Docker configuration.
> Refactor Automation Deployment to Use Environment Variables

- app/services/llm_handler.py
- return summary generated by llm
> return summary

- app/models/storage.py
- app/persistence/storage_service.py
- app/routes.py
- app/services/cypher_generator.py
- tests/integration/cypher/test_cypher_response.py
* **Node and Edge Count**:  Implemented logic to return both node count and edge count from the query results.
* **Bug Fixes**: Resolved a minor misspelling bug add guard check for the summary.
* Add created_at and updated_at fields, add node_type
> Node and Edge count and minor fixes

- app/routes.py
- app/services/cypher_generator.py
For issue No #43 
This update enhances the pagination functionality by including metadata fields in query responses to provide the total counts of nodes and edges matching the query criteria. This allows clients to better navigate and understand the scope of the dataset.
1. **New Metadata Fields:**
- `totalNodeCount`: Total nodes matching the query.
- `totalEdgeCount`: Total edges matching the query.
- `totalPages`: Total pages based on the `limit`.
- `maxPages`: Optional, representing the maximum allowable pages.
2. **Response Format Update:**
Added a `metadata` section to the paginated query response:
```json
{
"data": {
"nodes": [...],
"edges": [...]
},
"metadata": {
"totalNodeCount": 1,
"totalPages": 10,
"totalEdgeCount": 500,
"maxPages": 1000
}
}
```
To improve the pagination system …
> total nodes and edges counted

- app/__init__.py
- app/routes.py
fix issues where we load metta data even if the database is set as cypher
> Fix database type initalization

- app/prompts/summarizer_prompts.py
- app/routes.py
- app/services/cypher_generator.py
- app/services/llm_models.py
- update summarizer prompts
- lower max limit to 1000
- fix indentation bug 
- update model to gpt-4o-mini for openAi
> Bug fix, update summarizer prompts

- app/routes.py
- app/services/cypher_generator.py
Replaced UNION with CALL procedure to simplify query construction and make updates more manageable.
> Replace Union with CALL

- app/services/cypher_generator.py
* Update the query to count disjoint nodes
> Fix Node Count Issue

- app/models/storage.py
- app/persistence/storage_service.py
- app/routes.py
- app/services/cypher_generator.py
* Implemented functionality to calculate and return the count of nodes and edges grouped by their respective labels and types.
* Minor refactoring
> Count Node and Edge by Label

- app/services/cypher_generator.py
-  Handle failures in executing the count query without causing an error
> Handle Count Query Failure Gracefully

- app/routes.py
- app/services/cypher_generator.py
Added query string parameter, source, which supports two possible values: hypothesis and ai-assistant. The behavior based on the value of source is as follows:
- hypothesis:
The query will not be saved.
Title and summary generation will be skipped.
- ai assistant:
The response will only include the question, answer, and annotation ID.
Fix Issue related to incorrect edge count
> Add Source Query Parameter for Hypothesis and AI Assistant Calls

- app/services/cypher_generator.py
The ID in the edges  is generated by concatenating the source label, predicate, and target label using an underscore (_).
> Add Id to Edges

- app/lib/validator.py
- app/routes.py
- app/services/cypher_generator.py
- app/services/schema_data.py
- config/schema_config.yaml
Filters out parent nodes and their edges.
Replaces id in edges with edge_id.
> Refactor Schema for Frontend Lookup Table

- app/routes.py
- app/services/cypher_generator.py
Fix issue when source is not set for the endpont `GET /annotation/<id>`
Add source paramter to manipulate the process based on if source is ai-assistant, hypotesis service or just a request from the frontend
> Fix source not set errro

- app/services/cypher_generator.py
- Fix Neo4J syntax error due to skip and limit position
- Return empty list if the count query fails
> Fix Neo4j Query Syntax and Handle Count Query Failures Gracefully

- app/routes.py
- app/services/cypher_generator.py
* Add a new endpoint POST /annotation/<id> that accepts a question and annotation id from the query parameter and returns the answer based on the annotation we got from the id and the summary
> Add new endpoint that accepts question from ai assistant

- app/services/cypher_generator.py
- Return 0 node and edge count when the query fails to execute
- Separate total node and edge count and node and edge count by label
> Fix count issue

- app/models/storage.py
- app/persistence/storage_service.py
- app/routes.py
* Save json request in the mongodb database.
* Return the json request in the response when getting annotation by id and when making a request to /history endpoint
> Save Json Request

- app/routes.py
- app/services/cypher_generator.py
"Add optional matching in case of a call from hypothesis generation
> Add Optional Matching

- app/lib/validator.py
- requirements.txt
Add backend validation to disconnected graph
Fix #80
> Add Backend validation to disconnected graph

- app/lib/__init__.py
- app/lib/graph.py
- app/models/storage.py
- app/persistence/storage_service.py
- app/prompts/summarizer_prompts.py
- app/routes.py
- app/services/cypher_generator.py
- app/services/graph_handler.py
- app/services/llm_handler.py
- requirements.txt
* Implement Graph grouping algorithm that uses both node collapsing and edge collapsing
> Graph Grouping

- app/lib/graph.py
* Add properties of each node when collapsing
> Add Properties

- Data/graph_info.json
- app/__init__.py
- app/annotation_controller.py
- app/constants.py
- app/lib/__init__.py
- app/lib/auth.py
- app/lib/graph.py
- app/lib/utils.py
- app/models/storage.py
- app/persistence/storage_service.py
- app/routes.py
- app/services/cypher_generator.py
- app/services/metta_generator.py
- app/workers/task_handler.py
Graph Updates:
*  Improved the grouping algorithm to use edge_id instead of label while retaining labels for visualization.
*  Added a "group by label" feature when nodes lack connecting edges.
Status and WebSocket Enhancements:
*  Converted hardcoded status values to Enums.
*  Modified the /annotation/[id] endpoint to use WebSocket communication when the status is complete but the result is not in the cache.
*  Updated WebSocket authentication to require a token for connection.
Query and Annotation Improvements:
*  Removed the query generator feature that created queries for disconnected nodes or subgraphs.
*  Ensured thread safety when canceling annotations.
>  Improve Graph Processing, WebSocket Flow, and Annotation Safety

- app/__init__.py
- app/routes.py
- app/services/llm_models.py
- app/workers/__init__.py
- app/workers/task_handler.py
* remove the 0.1 second delay before starting a thread 
* Return the graph status if the process is finished before the user joins a room
> Optimize Thread Start Time & Improve Graph Status Handling"

- Data/count_info.json
- app/__init__.py
- app/constants.py
- app/lib/__init__.py
- app/lib/heuristic_sort.py
- app/routes.py
- app/services/cypher_generator.py
* Generate a query based on whether either the source or target has a property, and the count of the predicate.
* Break down the query into subqueries for faster processing. 
Note: the cypher query generator will generate this kind of query from now 
`MATCH  (n1:gene)-[p1:transcribed_to]-> (n2:transcript) WHERE n1.gene_name =~ '(?i)IGF1' WITH p1, n1, n2 MATCH  (n3:protein)-[p3:interacts_with]-> (n4:protein)  WITH p1, p3, n1, n3, n4, n2 MATCH  (n2:transcript)-[p2:translates_to]-> (n3:protein)  RETURN p1, p3, p2, n1, n3, n4, n2`
> Optimization: Heuristic-based Query Generation

- app/annotation_controller.py
- app/lib/__init__.py
- app/lib/graph.py
- app/lib/utils.py
- app/routes.py
* Add an endpoint to download the Excel file for the entire group, including only the grouped nodes.
* Fix redundant data fields in the response.
> Table Result Download

- app/lib/graph.py
- app/routes.py
- app/services/cypher_generator.py
* Replacing custom logic with NetworkX-based graph operations
* Improved node grouping based on shared connections
This change has increased the accuracy and made the graph easier to visualize.
from this : 
to this:
> Refactor Graph Visualization Algorithm to Use NetworkX for Improved Accuracy

- app/lib/auth.py
- app/routes.py
- app/services/llm_handler.py
* Allow annotation service to query and annotation without the llm key
* for the title if the llm key is not provided or invalid or out of quota use "Untitled" as a title for the summary make it "No summary available"
* Also fix issue with websocket integration
fixes #105 
fixes #107
> Feat: Optional LLM
